### ISSUE TITLE
missing `mmpose/version.py`

### ISSUE THREAD

**Issue by ShoufaChen** [HRNet/HRFormer#24]
Hi,

When I installed mmpose in this repo, I found there is no `mmpose/version.py` file.
```
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/home/chenshoufa/workspace/HRFormer/pose/setup.py", line 105, in <module>
        version=get_version(),
      File "/home/chenshoufa/workspace/HRFormer/pose/setup.py", line 14, in get_version
        with open(version_file, 'r') as f:
    FileNotFoundError: [Errno 2] No such file or directory: 'mmpose/version.py'

```

**Comment by aarushgupta** [comment]
Hey @ShoufaChen were you able to figure this out? I'm stuck on the same issue.

**Comment by ShoufaChen** [comment]
I solved this issue by adding a `version.py` at  `pose/mmpose/version.py`  which contains:

```
__version__ = '0.13.0'
short_version = __version__
```
